### ISSUE TITLE
predicitons for one video contaning 2-3 actions

### ISSUE THREAD

**Issue by bit-scientist** [mttr2021/MTTR#2]
Well, let me start with thanking you with this great work. It's awesome.

If, for example, I have a 20s-long video where several actions take place for 4-5s each. Is the model capable of predicting them as well? I mean, usually, models assign particular category to one video, but this case different, therefore I was wondering if it can predict outputs when one video with several actions is shown. Thank you.

**Comment by mttr2021** [comment]
Hi there,

Thank you for your interest in our work.
Following the RVOS task, MTTR is designed to attend to a single text query while processing a video. However, If you wish to track several objects (based on several text queries) in a single video, you can easily achieve that too using a simple inference loop. We demonstrate how this can be done with just a few lines of code in our recently published [Colab Demo](https://colab.research.google.com/drive/12p0jpSx3pJNfZk-y_L44yeHZlhsKVra-?usp=sharing).

Good luck :)
