### ISSUE TITLE
Can you provide visualization script?

### ISSUE THREAD

**Issue by sunggukcha** [mttr2021/MTTR#3]
Hello, great thanks to your work and publication.

Can you provide visualization script? I am trying and stucked in dealing 50 queries. Can you explain or refer how to choose which prediction out of the 50 is to be used?

**Comment by mttr2021** [comment]
Hi there,

Thank you for your interest in our work.
We have recently published an interactive demonstration of MTTR on [Google Colab](https://colab.research.google.com/drive/12p0jpSx3pJNfZk-y_L44yeHZlhsKVra-?usp=sharing).
I believe you will find everything you are looking for there. 

I'm closing this issue for now, but if you have any more questions feel free to ask :)

Good luck!
