### ISSUE TITLE
Can you tell me how many stages in your work

### ISSUE THREAD

**Issue by sutiankang** [mttr2021/MTTR#4]
Hello, great thanks to your work and publication.
Can you tell me how many stages in your work. I want to know when training a model, whether to use only one of the A2D-Sentences and JHMDB-Sentences data, or divide it into two stages. first use the A2D-Sentences dataset for training, and then use the JHMDB-Sentences dataset for training. Thank you.

**Comment by mttr2021** [comment]
Hi there,
Thank you for your interest in our work! We sincerely apologize for our delayed response.
In this project we included a separate torch dataset file for each RVOS dataset, so training needs to be run separately for each dataset (unless you manage to create a mixed torch dataset yourself or change the training code to support loading samples from multiple datasets in the same run). Note that nothing prevents you from training on one dataset and then use that model to train on another (however we did not try this ourselves).
With regards to JHMDB-Sentences, as described in our paper we use this dataset only for evaluation (after training on A2D-Sentences), so training is not officially supported for it at this time. Despite this, we believe you can add training support for it yourself with minor code modifications to our project (start with JHMDB's torch [dataset](https://github.com/mttr2021/MTTR/blob/main/datasets/jhmdb_sentences/jhmdb_sentences_dataset.py)).
We hope we were able to answer your question :)
