### ISSUE TITLE
Request for precomputed results on RVOS

### ISSUE THREAD

**Issue by JerryX1110** [mttr2021/MTTR#8]
Great work! Could you share the precomputed results on RVOS? Thanks! 👍

**Comment by mttr2021** [comment]
Hi there,
Thank you for your interest in our work! We sincerely apologize for our delayed response.
Can you please clarify your question? what do you mean by "precomputed results", and on what exactly? (RVOS is the name of our task).
Thanks

**Comment by JerryX1110** [comment]
Hi, "precomputed results" means the predictions (predicted segmentation masks) of MTTR on RVOS-related datasets including A2D-Sentences, JHMDB-Sentences, and Refer-YouTube-VOS dataset. Thanks!
